name: reviewdog

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  reviewdog:
    name: Biome
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check
        uses: mongolyy/reviewdog-action-biome@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
